package com.cheroliv.newpipe.scenarios

class AuthSessionSteps(private val world: NewpipeWorld) {

    // ------------------------------------------------------------------
    // Given
    // ------------------------------------------------------------------

    @Given("a Newpipe project with a client_secrets directory")
    fun projectWithClientSecrets() {
        world.createGradleProjectWithEmptySessions()
        assertThat(world.projectDir).exists()
        assertThat(world.projectDir!!.resolve("client_secrets"))
            .describedAs("client_secrets/ should have been created")
            .isDirectory
    }

    @Given("a Newpipe project wired to the real sessions.yml")
    fun projectWithRealSessions() {
        val sessionsFile = world.realSessionsFile()
        // Skip si sessions.yml absent ou sans refreshToken —
        // cohérent avec buildSessionManager qui retourne null dans ce cas
        assumeTrue(
            sessionsFile.exists(),
            "sessions.yml absent — scénario skippé (run: ./gradlew buildSessions)"
        )
        assumeTrue(
            sessionsFile.readText().lines()
                .filter { it.trim().startsWith("refreshToken:") }
                .any { !it.trim().endsWith("\"\"") && !it.trim().endsWith("''") && it.contains(":") && it.substringAfter(":").trim().isNotBlank() },
            "Aucun refreshToken dans sessions.yml — scénario skippé (run: ./gradlew authSessions)"
        )
        world.createGradleProjectWithRealSessions()
        assertThat(world.projectDir).exists()
    }

    @Given("a Newpipe project with a sessions.yml without refreshToken")
    fun projectWithEmptySessions() {
        world.createGradleProjectWithEmptySessions()
        assertThat(world.projectDir).exists()
        assertThat(world.projectDir!!.resolve("sessions.yml"))
            .describedAs("sessions.yml should exist with empty refreshToken")
            .exists()
    }

    // ------------------------------------------------------------------
    // When
    // ------------------------------------------------------------------

    @When("I am executing the task {string} in mock mode")
    fun runTaskInMockMode(taskName: String) = runBlocking {
        world.buildResult = GradleRunner.create()
            .withProjectDir(world.projectDir!!)
            .withArguments(
                taskName,
                "--stacktrace",
                "-D${DownloadMusicTask.MOCK_PROPERTY}=true"
            )
            .withPluginClasspath()
            .build()
    }

    // ------------------------------------------------------------------
    // Then / And
    // ------------------------------------------------------------------

    @Then("sessions.yml should exist in the project")
    fun sessionsFileShouldExist() {
        assertThat(world.projectDir!!.resolve("sessions.yml"))
            .describedAs("sessions.yml should have been generated by buildSessions")
            .exists()
    }

    @And("sessions.yml should contain the fake clientId")
    fun sessionsFileShouldContainClientId() {
        assertThat(world.projectDir!!.resolve("sessions.yml").readText())
            .describedAs("sessions.yml should contain the clientId extracted from the JSON")
            .contains(FAKE_CLIENT_ID)
    }

    @And("sessions.yml should contain an empty refreshToken")
    fun sessionsFileShouldHaveEmptyRefreshToken() {
        assertThat(world.projectDir!!.resolve("sessions.yml").readText())
            .describedAs("refreshToken should be empty — Device Flow not yet done")
            .contains("refreshToken: \"\"")
    }

    @And("the output should contain {string}")
    fun outputShouldContain(expected: String) {
        assertThat(world.buildResult?.output)
            .describedAs("Build output should contain: $expected")
            .contains(expected)
    }
}