package com.cheroliv.newpipe

import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import javax.inject.Inject

open class NewpipeExtension @Inject constructor(objects: ObjectFactory) {

    val configPath: Property<String> = objects.property(String::class.java)

    /**
     * Path to the directory containing Google OAuth2 JSON files downloaded
     * from Google Cloud Console (type "installed" / TV & Limited Input).
     * Add this directory to .gitignore — it contains client secrets.
     */
    val clientSecretsDir: Property<String> = objects
        .property(String::class.java)
        .convention("")

    /**
     * Path to sessions.yml — generated by [BuildSessionsTask], enriched
     * by [AuthSessionTask] with refreshTokens.
     * Add to .gitignore — it contains secrets.
     */
    val sessionsPath: Property<String> = objects
        .property(String::class.java)
        .convention("")

    val ffmpegDockerImage: Property<String> = objects
        .property(String::class.java)
        .convention(DEFAULT_FFMPEG_IMAGE)

    val forceDocker: Property<Boolean> = objects
        .property(Boolean::class.java)
        .convention(false)

    companion object {
        const val DEFAULT_FFMPEG_IMAGE = "jrottenberg/ffmpeg:4.4-alpine"
    }
}